#!/usr/bin/env bash

BASE="/home/Reneto/.emulationstation/themes/Pi-Station-X/_inc"
SRC="$BASE/overlay-arts"
DST="$BASE/collection-overlays"

mkdir -p "$DST"

move_art() {
    local name="$1"
    if [ -f "$SRC/$name.png" ]; then
        echo "Moviendo: $name.png"
        mv "$SRC/$name.png" "$DST/$name.png"
    else
        echo "No existe: $name.png"
    fi
}

# =========================
# COLECCIONES AUTOMÁTICAS
# =========================
move_art "auto-action"
move_art "auto-adult"
move_art "auto-adventure"
move_art "auto-beatemup"
move_art "auto-board"
move_art "auto-casual"
move_art "auto-fight"
move_art "auto-musicanddance"
move_art "auto-platform"
move_art "auto-racedriving"
move_art "auto-roleplayings"
move_art "auto-shootemup"
move_art "auto-shooter"
move_art "auto-simulation"
move_art "auto-sports"

# =========================
# FRANQUICIAS / SAGAS / PERSONAJES
# =========================
move_art "007"
move_art "aerotheacrobat"
move_art "aladdin"
move_art "alexkidd"
move_art "alisia"
move_art "assassinscreed"
move_art "asterix"
move_art "barbarian"
move_art "batman"
move_art "blackops"
move_art "bomberman"
move_art "bombjack"
move_art "borderlands"
move_art "brucelee"
move_art "bubsy"
move_art "bugsbunny"
move_art "captainamerica"
move_art "castlevania"
move_art "chess"
move_art "coolspot"
move_art "crashbandicoot"
move_art "crisiscore"
move_art "daffyduck"
move_art "darkstalkers"
move_art "devilmaycry"
move_art "dirgeofcerberus"
move_art "donkeykong"
move_art "doom"
move_art "doom3"
move_art "doubledragon"
move_art "dragonball"
move_art "dragonquest"
move_art "dragonslair"
move_art "earthwormjim"
move_art "fatalfury"
move_art "finalfantasy"
move_art "finalfantasyix"
move_art "finalfantasyvi"
move_art "finalfantasyviii"
move_art "finalfantasyx"
move_art "fireemblem"
move_art "fistofthenorthstar"
move_art "flash"
move_art "flashback"
move_art "flintstones"
move_art "frogger"
move_art "gearsofwar"
move_art "ghostoftsushima"
move_art "ghostsgoblins"
move_art "godofwar"
move_art "goldenaxe"
move_art "goonies"
move_art "guiltygearx"
move_art "gundam"
move_art "halo"
move_art "hang-on"
move_art "he-man"
move_art "indianajones"
move_art "kingdomhearts"
move_art "kingoffighters"
move_art "knuckles"
move_art "lastofus"
move_art "lemmings"
move_art "libertycity"
move_art "luckyluke"
move_art "lunar"
move_art "mario"
move_art "mazinger"
move_art "medievil"
move_art "megaman"
move_art "metalgear"
move_art "metalslug"
move_art "metroid"
move_art "mickeymouse"
move_art "monkeyisland"
move_art "mortalkombat"
move_art "naruto"
move_art "navymoves"
move_art "nightsintodreams"
move_art "ninjaturtles"
move_art "onepiece"
move_art "onimusha"
move_art "pacman"
move_art "phantasystar"
move_art "pinocchio"
move_art "pokemon"
move_art "popeye"
move_art "ratchet"
move_art "rayman"
move_art "residentevil"
move_art "roadrash"
move_art "robocop"
move_art "rogerrabbit"
move_art "r-type"
move_art "samuraishodown"
move_art "sanandreas"
move_art "scooby"
move_art "shadowofthebeast"
move_art "shenmue"
move_art "simpsons"
move_art "sims"
move_art "smurfs"
move_art "snoopy"
move_art "sonic"
move_art "sonic-mania"
move_art "sonicretro"
move_art "sonicthehedgehog"
move_art "soulcalibur"
move_art "spacechannel5"
move_art "spiderman"
move_art "splintercell"
move_art "spongebob"
move_art "starfox"
move_art "starwars"
move_art "streetfighter"
move_art "streetsofrage"
move_art "strider"
move_art "suikoden"
move_art "superman"
move_art "superpang"
move_art "tekken"
move_art "tetris"
move_art "tombraider"
move_art "tomjerry"
move_art "toystory"
move_art "tron"
move_art "virtuafighter"
move_art "wackyraces"
move_art "wario"
move_art "wonderboy"
move_art "yojimbo"
move_art "ys"
move_art "zelda"
move_art "zeldaocarina"
move_art "zool"

echo
echo "Listo. Colecciones movidas a:"
echo "$DST"